/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include"stm32f405xx.h"

class USART
{
private:
    USART() {}

public:
    static USART& instance()
    {
        static USART inst;
        return inst;
    }

    USART(const USART&) = delete;
    USART& operator=(const USART&) = delete;

    void write_char(char c)
    {
        while (!(USART3->SR & (1 << 7))); // TXE
        USART3->DR = c;
    }

    void write_string(const char* str)
    {
        while (*str)
        {
            write_char(*str++);
        }
    }
};



void gpio_init()
{
    RCC->AHB1ENR |= (1 << 3);     // Enable GPIOD clock

    GPIOD->MODER &= ~(3 << (12 * 2));
    GPIOD->MODER |=  (1 << (12 * 2));  // PD12 as output
}



void delay()
{
    for (volatile int i = 0; i < 500000; i++);
}

int main()
{
    auto& uart = USART::instance();

    gpio_init();

    uart.write_string("System Started\n");

    while (1)
    {
        GPIOD->ODR ^= (1 << 12);   // Toggle LED

        uart.write_string("LED TOGGLED\n");

        delay();
    }
}
