/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************/
#include<cstdint>
#include "stm32f405xx.h"

uint8_t ch;
void USART1_init();
void delay(uint8_t ms);
void USART1_write(uint8_t ch);
uint8_t USART1_read(void);
void USART1_string(const char *str);

int main()
{
	USART1_init();

	while(true)
	{
		USART1_write('M');
		 ch=USART1_read();

		USART1_write(ch);

		//USART1_string("MANDA MANOHAR\n");
		delay(200);
	}

}


void USART1_init()
{
	// enable clock

	RCC->APB2ENR |=(1U<<4);// enable usart1 //
	RCC->AHB1ENR |=(1U<<1);// enable GPIOB


	//tx and rx settings
	 GPIOB->MODER &=~(3U<<12);  //tx b6 so each bit two
	 GPIOB->MODER |= (1U<<13); // set altrantive functionality

	 GPIOB->AFR[0] &= ~(0xF<<24); // 6 & 7 so its low AFR each is four bits
	 GPIOB->AFR[0]|= (0x7<<24); // afternative pin is AFR7 so set 0x7

	 //Rx setting
	 GPIOB->MODER &=~(3U<<14);  //rx b7 so each bit two
	 GPIOB->MODER |= (1U<<15); // set altrantive functionality

	 GPIOB->AFR[0] &= ~(0xF<<28); // 6 & 7 so its low AFR each is four bits
	 GPIOB->AFR[0] |= (0x7<<28);//AFR pin set AFR so set 0x7

	  //usart1 settings

	  // tX & RX enable

	  USART1->BRR = 0x0683;// set the buatrate
	  USART1->CR1 |=(1U<<2);
	  USART1->CR1 |=(1U<<3);
	  USART1->CR1 |=(1U<<13); //UE enable

}

void delay(uint8_t ms)
{

	for( ;ms>0;ms--)
		for(uint32_t i=0;i<2000;i++);
}

void USART1_write(uint8_t ch)
{

	while(!(USART1->SR & (1U<<7))); // chk TXE is tx register empty or not

	USART1->DR =ch;

	while(! (USART1->SR & (1U<<6))); // check tx is completed or not

}

uint8_t USART1_read()
{
	while(!(USART1->SR & (1U<<5)));

	return USART1->DR;
}

void USART1_string(const char *str)
{

	while(*str)
	{
		USART1_write(*str);
		str++;
	}

}
