/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include<cstdint>
#include"stm32f405xx.h"
#include"LCD.h"

int main()
{
	LCD l;
	l.lcd_contrl();
	l.LCD_Init();
	l.set_cursor(0,0);
	l.write_string("HELLO");

	l.set_cursor(1,0);
	l.write_string("STM32");
	l.set_cursor(1,7);
	l.write_num(100);

		while(1);

}
