/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include <lcd.h>
#include <cmn.h>


#define GPIO_BTN	GPIOA
#define PIN_BTN		15

void CountInit(void)
{
	RCC->AHB1ENR |=(RCC_AHB1ENR_GPIOAEN); // A15 is connected with SW4
	SetAltFunc(GPIO_BTN,PIN_BTN,1);
    GPIOA->AFR[1] =(0x10000000);

	RCC->APB1ENR|=RCC_APB1ENR_TIM2EN; //TIM2 clock enable

	TIM2->CR1 &=~(TIM_CR1_CEN); // disable counter before making any changes in its bit
	TIM2->SMCR |=(1<<14)|(1<<15)|(1<<4)|(1<<5)|(1<<6); // External trigger enabled(4,5,6), ETP=1 (bit 15) falling edge is required, ECE =1
	TIM2->CR1 |=(TIM_CR1_CEN); //enable counter

}



int main(void)
{
	char str[20]={0};
	LcdInit();
	CountInit();
	lprint(0x80, "Hello");
	while(1)
	{
	 sprintf(str,"Count:%4ld",TIM2->CNT);
	 lprint(0xc0, str);
	}
}
